### ISSUE TITLE
非常感谢你提供这么棒的工具，但是测试发现了很大的bug,希望能尽快修复，谢谢！

### ISSUE THREAD

**Issue by yuan78** [Lafeng/deblocus#22]
非常感谢你提供这么棒的工具，但是测试发现了很大的bug,希望能尽快修复，谢谢！
具体情况如下:
1. 访问gmail时，gmail永远处于载入进度条状态，貌似卡死，无法进入邮箱界面
2. 访问youtube, 广告过后，播放窗口一直转圈圈无法播放视频
3. 连接不稳定，貌似很容易就卡死。

这些问题使用Shadowsocks时没有出现，

本人客户端： win7 , 用户凭据都已经载入deblocus.d5c文件

**Comment by vickery** [comment]
着实吓人一跳，先说这几个问题：
- 你用的那个版本？
- 到你deblocus server之间的Ping延迟多少、丢包率高低？
- 你的浏览器用的socks5还是Http方式？

然后开启详细日志：
- 在client/server两边加上参数`-v=4 -logdir=logs`

其中logs是一个可读写目录，将会输出大量的log到这个目录下，测几遍有问题的访问，稍等1，2分钟，然后把log打包发出来。

**Comment by yuan78** [comment]
1. 我用的是v0.9.2520-dev这个版本，我不知道deblocus和deblocus-dev有什么区别，一个更新时间是9.9，一个更新时间是9.16
2. 我这边是win7,不知道怎么使用MTR工具，总得来看ping值在180ms, 基本不丢包，线路没有问题
3. 浏览器使用sock 5 代理

我试了一下，-v=4 -logdir=logs 这个参数，只能在linux server端添加； 客户端windows gui界面我添加不了，我后来试图使用批处理命令行的方式添加日志参数，结果报错。所以客户端日志无法导出成文件

另外你那个服务端的deblocus.d5c的配置文件貌似有个无效的配置项：Denytarge, 会导致报错： unrecognized symbol, 所以我把它删掉了

**Comment by vickery** [comment]
是这样的，deblocus下面是经过较长时间测试的公开版本，deblocus-dev是开发分支上自动编译的，通常dev下面包括最新的feature也代表了不够稳定。
你刚说的情况的确是最新的dev版本中的问题，刚才的提交已经修复。
另外，TargetDeny是dev版本增加的一个新选项，文档还没有改，用途是拦截代理不能访问某国网络，比如TargetDeny  HK，这就代表了，服务端会拒绝到HK的请求。
如果你希望使用这个feature就用现在最后一个dev，如果不想，就是deblocus稳定发布的版本。

**Comment by yuan78** [comment]
Good job! 太感谢了！
另外想提一个需求：就是希望能增加server端的后台运行功能（dameon），否则，putty窗口一关， server的服务也就随之断线了。

谢谢！

**Comment by vickery** [comment]
这个其实在文档中就有提到，进程fork一个daemon进程不是一个通用跨平台的方法，因此推荐在server上最简单的事通过tmux/screen可以保持运行任何程序。
自动一点的做法，写一个upstart/systemd的脚本，由linux当作一个service来管理。

**Comment by yuan78** [comment]
能帮忙告知如何写upstart/systemd的脚本把deblocus变成系统service的具体命令行吗？另外debian系的好像不能用sytemd吧？

还有一个问题，请问deblocus如何才能实现PAC功能自动bypass掉国内网站不走代理，谢谢！

**Comment by vickery** [comment]
debian 8是systemd，6,7的就写init脚本，可以参考/etc/init.d/nginx的写法，关键就是这几句
`start-stop-daemon --start --background --exec /path__deblocus`
PAC管理以后会纳入进来，一会贴一个简单的PAC示意到wiki里。
