### ISSUE TITLE
handshake error read tcp 

### ISSUE THREAD

**Issue by gandalfwong** [Lafeng/deblocus#29]
客户端连接时服务器显示handshake error read tcp x.x.x.x:xxxx->y.y.y.y:yyyy: i/o timeout

x, y 是我的ip.  会不会是因为我的vps用了ss的优化手段?

**Comment by vickery** [comment]
两边的版本是多少？配置是什么？

**Comment by gandalfwong** [comment]
你一句话提醒我。 原来是因为windows端的版本比服务器端低的原因！ 不错的软件，谢谢！
