### ISSUE TITLE
after running "GOPATH=`pwd` go get github.com/Lafeng/deblocus",encounter error

### ISSUE THREAD

**Issue by luckypoem** [Lafeng/deblocus#30]
root@AR:~# GOPATH=`pwd` go get github.com/Lafeng/deblocus
go/src/github.com/Lafeng/deblocus/bootContext.go:6:2: /root/go/src/github.com/Lafeng/deblocus/crypto/chacha.go: malformed #cgo argument: -L${SRCDIR}
root@AR:~#

how to fix it?thank u

**Comment by vickery** [comment]
show me `go version` and `uname -a`

**Comment by luckypoem** [comment]
hi.
root@AR:~# go version
go version go1.4.2 linux/386
root@AR:~# uname -a
Linux AR 2.6.32-042stab103.6 #1 SMP Wed Jan 21 13:07:39 MSK 2015 i686 GNU/Linux
root@AR:~#

**Comment by spance** [comment]
Require go 1.5 and above.
And 64-bit OS is strongly recommended.

**Comment by vickery** [comment]
Require go 1.5 and above, and 64-bit OS is strongly recommended.

**Comment by luckypoem** [comment]
hi.
我删了GO1.4，装了go1.5,翻@#墙成功，速度很快。可否提供mac客户端程序呢？

**Comment by vickery** [comment]
mac客户端在release中有。
另外，不讨论敏感词汇。

**Comment by luckypoem** [comment]
hi.
我在mac中也“特殊上网”成功，只是下载的文件https://dl.soez.xyz/deblocus/deblocus-0.11.2810b-osx-x64.tar.xz解压出来后，就是一个孤零零的deblocus文件。我想请教一下，你是怎么把这个linux版的deblocus文件（https://dl.soez.xyz/deblocus/deblocus-0.11.2810b-linux-x64.tar.xz）转换为osx版的deblocus文件（https://dl.soez.xyz/deblocus/deblocus-0.11.2810b-osx-x64.tar.xz）的？
谢谢回复

**Comment by vickery** [comment]
这个“孤零零”用的好！deblocus的目标就是这个，就要足够的轻快干净，并且除了配置文件外不读写任何文件。
解压出来，在终端上执行，就和执行ping一样。
你下的那个不是转换出来，是在mac平台原生编译出来的。

**Comment by luckypoem** [comment]
hi.
你一定很熟悉Mac。
我刚接触Mac，想安装mac下的go环境。
https://storage.googleapis.com...
from https://golang.org/dl

在mac下，go的默认安装路径为/usr/local/go/
yudeMacBook-Air:~ brite$ cd /usr/local/go
yudeMacBook-Air:go brite$ ls
AUTHORS PATENTS bin lib src
CONTRIBUTING.md README.md blog misc test
CONTRIBUTORS VERSION doc pkg
LICENSE api favicon.ico robots.txt
yudeMacBook-Air:go brite$ ls bin
go godoc gofmt
yudeMacBook-Air:go brite$
mac系统根linux系统一样，也需要设置GOPATH.我是这样设置的：
sudo nano /etc/profile
在文件的末尾加上：
export GOROOT=/usr/local/go/
export GOBIN="$GOROOT/bin"
PATH=$PATH:$GOROOT/bin/
export PATH=$PATH:$GOROOT/bin/
GOPATH=/usr/local/mygo/
export GOPATH=/usr/local/mygo/
保存文件。然后运行：
. /etc/profile

但是运行go get 命令，提示“$GOPATH not set”：

yudeMacBook-Air:mygo brite$ sudo go get github.com/Lafeng/deblocus
package github.com/Lafeng/deblocus: cannot download, $GOPATH not set. For more details see: go help gopath
yudeMacBook-Air:mygo brite$

很是头痛。你能否亲自在你的mac机子上试试,看看能否成功运行go get 命令？
非常感谢你的答复.

**Comment by luckypoem** [comment]
是我修改 /etc/profile时，哪里修改得不正确吗

**Comment by vickery** [comment]
系统环境变量里面只需要设置一个GOROOT到go的目录，再把GOROOT/bin加入到PATH就够了
在用的时候，临时设置GOPATH会比较灵活，就是wiki里面讲的
```GOPATH=`pwd` go get -v ........```

**Comment by luckypoem** [comment]
HI.
yudeMacBook-Air:~ yuming$ cat /etc/profile
# System-wide .profile for sh(1)

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

if [ "${BASH-no}" != "no" ]; then
	[ -r /etc/bashrc ] && . /etc/bashrc
fi

export GOROOT=/usr/local/go/
export GOBIN="$GOROOT/bin"
PATH=$PATH:$GOROOT/bin/
export PATH=$PATH:$GOROOT/bin/

yudeMacBook-Air:~ yuming$
yudeMacBook-Air:~ yuming$ GOPATH=`pwd` go get github.com/Lafeng/deblocus
go install github.com/Lafeng/deblocus: open /usr/local/go/bin/deblocus: permission denied
yudeMacBook-Air:~ yuming$

how to fix it?
tks for ur help!

**Comment by vickery** [comment]
在home下创建或者cd到可rw的地方
```
cd ~
mkdir deblocus
cd deblocus
GOPATH=`pwd` go get -v github.com/Lafeng/deblocus
```

**Comment by luckypoem** [comment]
hi,
操作成功，谢谢。
你所说的osx版的deblocus文件（https://dl.soez.xyz/deblocus/deblocus-0.11.2810b-osx-x64.tar.xz）“是在mac平台原生编译出来的”，就是像上面这样编译出来的吗？

**Comment by vickery** [comment]
是的。

**Comment by luckypoem** [comment]
hi.
root@VM:~/go/bin# ./deblocus
No such file [deblocus.d5c; /root/go/bin/deblocus.d5c; /root/deblocus.d5c; /etc/deblocus/deblocus.d5c]
Create/put config in typical path or indicate it explicitly.
root@VM:~/go/bin# ./deblocus --config deblocus.d5s
W 1026 22:41:35] Please read https://github.com/Lafeng/delocus/wiki to learn more.
E 1026 22:41:35] Unrecognized directives at line: Auth               file:///etc/deblocus/user.conf
F 1026 22:41:35] Exiting.
root@VM:~/go/bin# cat deblocus.d5s
# -----------------------------
# deblocus server configuration
# -----------------------------

Auth               file:///etc/deblocus/user.conf
Cipher             AES256CFB
DenyDest           OFF
Listen             :9008
ServerName         myserver
Verbose            1

### Please take good care of this secret file during the server life cycle.
### DO NOT modify the following lines, unless you known what will happen.

-----BEGIN deblocus/SERVER-PRIVATEKEY-----
MIIEowIBAAKCAQEA9GlfSfOm3UAXeTMlg3JhG5QnB7RYP+owrRrP0iq0UWQleYZ1
。。。
-----END deblocus/SERVER-PRIVATEKEY-----
root@VM:~/go/bin# cat /etc/deblocus/user.conf
surmount:我设置的密码
root@VM:~/go/bin#

怎么回事呢？莫名其妙就不正常了

**Comment by vickery** [comment]
你之前可能用的0.11，从0.12之后改了加密部分，把`Cipher AES256CFB`改成这几个之一 AES128CTR AES192CTR AES256CTR AES128OFB AES256OFB CHACHA12 CHACHA20

**Comment by luckypoem** [comment]
看不明白。我之前用的是0.11-2810beta，跟新版（0.12版）有什么关系呢？具体该如何解决我的问题呢？
谢谢

**Comment by vickery** [comment]
server端需要`-serv`参数，另外，请升到最新0.12.

**Comment by luckypoem** [comment]
hi.
哦，知道为什么了。原来是在vps 上应该运行：./deblocus -serv -v=1 而非./deblocus
如何升到最新0.12.？先删除旧版？删掉/root/go/bin/deblocus和/root/go/bin/deblocus.d5s就删除干净了吗？

**Comment by vickery** [comment]
旧的程序删掉，新的下回来换上，配置复用。
到0.12有个配置变化，所以在配置中把`Cipher`项改一下，具体看wiki.
