### ISSUE TITLE
deblocus_312_9879295_linux-amd64.tgz 运行错误

### ISSUE THREAD

**Issue by yuan78** [Lafeng/deblocus#31]
[root@vultr ~]# ./deblocus -serv
 * Maybe there is an issue of some incompatible alterations caused.
 * Please read https://github.com/Lafeng/delocus/wiki to learn more.
F 1019 08:35:20] Unsupported cipher AES256CFB

**Comment by vickery** [comment]
dev分支上已经更换了aes实现，可用的aes方法有：
aes128ctr aes192ctr aes256ctr aes128ofb aes256ofb

**Comment by yuan78** [comment]
aes是ofb不是cfb结尾了？

**Comment by fd74a05d0b** [comment]
dev可用cipher：https://github.com/Lafeng/deblocus/blob/dev/tunnel/cipher.go#L64

**Comment by yuan78** [comment]
我试过了aesxxxctr的不行，很容易卡死。aesxxxofb的可以，chachaxx的没有试

**Comment by vickery** [comment]
不知道你说的卡死是不是网络重传等待造成的，但肯定不是加密方法导致的。

就加密性能而言，当cpu支持aes指令时，
aes128ctr > aes192ctr > aes256ctr > chacha12 > chacha20 > aes128ofb > aes256ofb
当cpu不支持aes指令时，
chacha12 > chacha20 > aes128ctr > aes192ctr > aes256ctr > aes128ofb > aes256ofb

另外，当tunnel吞吐未达到100Mbps以上时，这些加密方法之间的性能差异可以忽略不计。

**Comment by yuan78** [comment]
卡死就是这样的：
SERVER_NAME~45.63.123.194:9008 successfully
I1019 22:00:37.663163    5872 client.go:156] Tun SERVER_NAME-L2605 is established
I1019 22:00:37.770169    5872 client.go:156] Tun SERVER_NAME-L2606 is established
I1019 22:00:38.307200    5872 multiplexer.go:279] HTTP/T->[www.google.com:443] from=127.0.0.1 sid=1
I1019 22:00:38.309200    5872 multiplexer.go:279] HTTP/T->[www.youtube.com:443] from=127.0.0.1 sid=2
W1019 22:00:39.210252    5872 multiplexer.go:338] Read tunnel SERVER_NAME~X.X.X.X:9008 read tcp 192.168.1.100:2606->X.X.X.X:9008: wsarecv: An existing connection was forcibly closed by the remote host.
E1019 22:00:39.211252    5872 client.go:163] Tun SERVER_NAME-L2606 was disconnected, Reconnect after 5s
I1019 22:00:44.297543    5872 client.go:156] Tun SERVER_NAME-L2610 is established
日志不滚动了，网页也打不开了。
但是如果不通过deblocus monitor启动,只运行deblocus就没有这问题

**Comment by vickery** [comment]
22:00:39 出现连接不稳定，因为超时对端没有响应所以连接关闭重连。
22:00:44 重连成功。
22:07:43 不知何原因被掐断，此时又重新运行，然后端口占用，一般是被kill后发生，要稍等一会操作系统释放这个socket控制权。
Exited 2015-10-19 22:07:43  已经退出，当然所有代理请求都不通了。
应该能看出来了，这些都与加密无关。
