### ISSUE TITLE
可以像shadowsocks一样提供各个平台的版本吗？

### ISSUE THREAD

**Issue by ohyeah521** [Lafeng/deblocus#32]
如题：这样就需要开发人员提供代码规范，设计文档，然后其它开发人员才能参与进来，提供Openwrt，Python，Ruby，等语言的开发程序。

**Comment by vickery** [comment]
目前release中就有amd64下三个平台的版本，而且dev版本中增加了aarch64(arm64)的优化实现，主流平台下应该是基本够用，其它平台即使可以编译通过也可能不是最优实现。

不赞成支持openwrt和移动平台，因为这些平台上普遍存在着计算资源有限、电力资源有限、运行优先级和时机有限，而且在设计上有长连接，这些都不适合移动设备平台，从另外一个角度看，dbc无论服务端还是客户端，都是一个服务提供者角色，在一个受限的移动平台上，应该尽可能的享受服务做服务消费者，而不应该以有限的资源来提供服务，而且这些设备上也难以稳定的提供服务，更不说高效了。

技术细节和文档的问题，因为考虑到一些特殊的原因，暂时不准备完全透明出来，而且也没有精力，有兴趣的可以看代码也可以邮件讨论。

还有你提到的python ruby等语言开发是什么意思？

**Comment by ohyeah521** [comment]
就是说使用python 再开发一个，便于移植，既然这个程序设计不是为了移动平台的，那么后续的也不用考虑了。感谢解答。
