### ISSUE TITLE
错误问题

### ISSUE THREAD

**Issue by hehehym** [Lafeng/deblocus#34]
Error: D5Server is unreachable. Retry after 5s
出现这个问题是怎么解决?还有那个客户端打印认证信息那里如果在win系统是直接用.txt格式的文件命名成deblocus.d5c ?? 还有那个user.conf好像没用啊...弄了好久都搞不明白怎么用,求解~~

**Comment by vickery** [comment]
错误是无法连接服务器，其它问题先仔细阅读wiki.

**Comment by fd74a05d0b** [comment]
Issue expired.
