### ISSUE TITLE
服务器端异常退出

### ISSUE THREAD

**Issue by gachoyi** [Lafeng/deblocus#37]
[deblocus_log.txt](https://github.com/Lafeng/deblocus/files/53421/deblocus_log.txt)

运行环境：
Linux 2.6.32-042stab108.5 #1 SMP Wed Jun 17 20:20:17 MSK 2015 x86_64 GNU/Linux
vps配置：
openvz，128MB内存，128MB swap，10GB存储。
memory usage和swap usage都比较低。

**Comment by vickery** [comment]
这个错误不太容易重现，刚想到了一个问题，晚上更新一下再观察吧

**Comment by vickery** [comment]
先试一下这个版本，还请你观察几天后在回复结果。
可以从dev上自己编译，或者从https://dl.soez.xyz/deblocus-dev/下载自动编译的。

**Comment by gachoyi** [comment]
用了几天都没再出现这个错误。
之前的话每天都有个几次。
感觉上应该是解决了吧。

**Comment by vickery** [comment]
多谢反馈。
看样子你那的连接可能是频繁断开，也要考虑下链路问题了。

**Comment by gachoyi** [comment]
queue.go:361] Write edge(<-live.github.com:443) error(write tcp 127.0.0.1:1080->127.0.0.1:52558: wsasend: An established connection was aborted by the software in your host machine.). Frame{sid=3326 act=21 len=62}

现在在client端的日志中有不少这样的错误。
client端是win10 64位。使用的deblocus版本和服务器端一致。

**Comment by vickery** [comment]
这个是正常的warning，app建立了连接后提前关闭了，然后deblocus会对这种能够情况输出这种类型Log
一般来说，可能是app建立连接发送了请求，等了一段时间未响应它就关闭了，其实可能是链路上有严重丢包有高延迟等，底层一直在等待或重传，总之来说，要么是请求方app等的太少，要么就是网络链路的回馈太慢，或者app刻意发送请求而不要响应。
如果log中有大量的disconnect或者应用感知上很慢，那就可以确定是链路通信质量问题了。

**Comment by gachoyi** [comment]
行，那我就关了。等有好的vps再试试。
