### ISSUE TITLE
cli.go DEPRECATED Action signature cause error

### ISSUE THREAD

**Issue by LazyZhu** [Lafeng/deblocus#42]
./deblocus -V
deblocus version: v0.13.4780
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by vickery** [comment]
Use the latest dev branch, or switch to a old version of codegangsta/cli.
And we will consider using golang vendor feature to cope with some bad changes of dependencies.

**Comment by LazyZhu** [comment]
Tested ok.
