### ISSUE TITLE
0.13.5970-beta: binary cannot run on alpine linux ( "no such file or directory" )

### ISSUE THREAD

**Issue by lunaset** [Lafeng/deblocus#44]
**update**: i find the binary built for 32-bit architecture can works on alpine properly, which can be a temporary solution. it sounds weird ,but it works.

I've just tried to run deblocus on alpine linux ,and encountered a confusing problem :
```
$ uname -a
Linux c818c6bd1f8a 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 Linux
$ apk add --no-cache curl tar xz
...
OK: 62 MiB in 34 packages
$ curl -SL "https://github.com/Lafeng/deblocus/releases/download/0.13.5970b/deblocus-0.13.5970b-linux-amd64.tar.xz" -o deblocus.tar.xz && tar -xJf deblocus.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614    0   614    0     0   1380      0 --:--:-- --:--:-- --:--:--  1389
100 2662k  100 2662k    0     0  1684k      0  0:00:01  0:00:01 --:--:-- 5347k
$ ./deblocus
bash: ./deblocus: No such file or directory
$ file ./deblocus
./deblocus: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ldlinux-x86-64.so.2, for GNU/Linux 2.6.26, BuildID[sha1]=d75a5e12ff18b86e05f256b066482f4df6efb464, not stripped
```
As seen, the binary file `deblocus `exists ,but when you try to execute it you would be told that the file doesn't exist. I guess some dependences might be missing and tried troubleshooting , but it doesn't work.

Any thoughts on this?

(binary source : github.com/Lafeng/deblocus/releases for linux-amd64)

**Comment by 07d6** [comment]
Alpine Linux uses musl libc while the releases are built against glibc. You have to compile it yourself.

**Comment by lunaset** [comment]
@07d6 
I've compile from source myself using below cmd, and now the problem get solved.
```CGO_ENABLED=0 GOPATH=`pwd` GOOS=linux GOARCH=amd64 go get github.com/Lafeng/deblocus```
thanks a lot :)

**Comment by lunaset** [comment]
solved
