### ISSUE TITLE
开机启动

### ISSUE THREAD

**Issue by gttwork** [Lafeng/deblocus#45]
您好！
如何才能实现服务端开机启动？我搜索了几个教程都没有成功，不知道什么原因。
系统为debian 7.
感谢！

**Comment by vickery** [comment]
这里有一篇文档，可以帮助你 写一个service脚本 https://gist.github.com/naholyr/4275302

**Comment by gttwork** [comment]
非常感谢！我要好好学一下。希望能够成功。
